# Generated by Django 5.1.1 on 2024-09-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                          insert into store_collection (title) values ('Summersale');
                          """, """
                          delete from store_collection where title='Summersale';
                          """)
    ]
